# Generated by Django 6.0.7 on 2026-08-02 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        ('developers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('rating', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
                ('metacritic_score', models.IntegerField(blank=True, null=True)),
                ('background_image', models.URLField(blank=True)),
                ('platforms', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('developers', models.ManyToManyField(related_name='games', to='developers.developer')),
                ('genres', models.ManyToManyField(related_name='games', to='categories.category')),
            ],
        ),
    ]
